### ISSUE TITLE
Submit doesn't find tmc-testcourse's exercises

### ISSUE THREAD

**Issue by JaniL** [rage/tmc-cli#76]
Right now `tmc submit`is unable to find tmc-testcourse's exercise 'trivial'.

![Imgur](http://i.imgur.com/pLBB9T0.png)

Submitting exercises from courses such as ohpe has no such problem:

![Imgur](http://i.imgur.com/fJ9NpXI.png)

**Comment by zinkko** [comment]
Could not reproduce

**Comment by UMTti** [comment]
could not reproduce also so I close this issue
