### ISSUE TITLE
When user gives first command, tmc-client.jar is started but no command is invoked

### ISSUE THREAD

**Issue by samutamm** [rage/tmc-cli#78]
There is no java processes running (killall java) and scripts/config is empty. When user gives command "tmc help", .jar is started but no output comes to terminal. User has to give "tmc help" command again to see the result.

**Comment by JaniL** [comment]
Apparently this started when we took `sleep 1` off from the startup.sh, as we thought that the server starts pretty quickly. This is not however the case on some slower computers. (tapahtuu mm. pajakoneilla :trollface:)

**Comment by zinkko** [comment]
Added `sleep 0.5` to startup.sh, to give the server time to start
